server:
#  web应用
  port: 8002

spring:
  application:
#  应用名
    name: gate-way
  profiles:
    active: dev
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: flyway

#zuul:
#  routes:
#    api-a-url:
#      path: /api-a/**
#      serviceId: client

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8001/eureka/'